name: compile test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with:
          submodules: true # Ensures submodules are cloned
      - run: git submodule update --init --recursive
      - run: make